name: Build package

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - uses: purcell/setup-emacs@v3.0
        with:
          version: 27.2
      - uses: conao3/setup-cask@master
        with:
          version: 'snapshot'
      - name: Install dependencies
        run: |
          cask install
      - name: Byte-compile
        run: |
          cask build
      - name: Check if elc-file was created (Byte-compile step never returns non-0 status code)
        run: |
          cat gba-debug.elc
